### ISSUE TITLE
Is it possible to add a new feature?

### ISSUE THREAD

**Issue by Vitalyplay** [Exiled-Team/DiscordIntegration#54]
It would be cool to add the ability not to log the admin actions of certain administrators, for example, I have many trusted administrators whom I trust, but even more beginners, and in order not to clog the logs and better monitor them, it would be cool to have such an opportunity.

**Comment by joker-119** [comment]
Possible, yes. Will it get added? Probably not right away.
I'm quit busy with EXILED itself and a lot of other projects, since this is an extremely niche feature that most owners won't use, it'll be quite low on my priorities for awhile. But another dev is welcome to add it in a PR and I'll accept it.
