### ISSUE TITLE
[BUG] Bot receive corrupted JSON data

### ISSUE THREAD

**Issue by ITeMbI4** [Exiled-Team/DiscordIntegration#99]
**Describe the bug**
Precondition: I have my own fork of discord integration (this is the same, but with more debug)

Sometimes bot receive corrupted JSON data from SCP server like:
```{"$type":"SCP_Discord.RemoteCommand, SCPDi```
or
```{"$type":"SCP_Discord.RemoteCommand, SCPDiscord","action":0,"parameters":[0,":tada: **Adjust player Korna (REDACTED STEAM@ste```

Tested within localhost!

**To Reproduce**
1. Run SCP server with installed DiscordIntegration
2. Run SCP Bot
3. Wait when corrupted data appears (it's random)

**Expected behavior**
Bot always receive correct and full data

**Server logs**
Please include a pastebin of your localadmin log file (or both MA_log and SCP_log files if you use MultiAdmin) from the time in which the bug occured

**EXILED Version ("latest" is not a version):**
5.2.1

**Comment by ITeMbI4** [comment]
I have added this to catch in `OnReceived` method in bot
![image](https://user-images.githubusercontent.com/46756889/172685394-1ad61fd5-fc7b-4c96-af18-fc4af3821678.png)

![image](https://user-images.githubusercontent.com/46756889/172685486-ee838bab-d04f-41a9-bc4d-2ae59ca03081.png)

**Comment by joker-119** [comment]
Interesting. It's not corrupted, it's just receiving the data in partial blocks for some reason, but also, the type `SCP_Discord.RemoteCommand` is not valid. Make sure you've updated the plugin aswell, because in none of my testing has `DiscordIntegration` sent partial info in the tcp stream before. Like literally in the entirety of EXILED DiscordIntegration I've never seen it send a partial message to the bot, and the type shown here makes me think you're just using the wrong plugin, as the `SCPDiscord` type has also never existing in DI.
